apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacitypythonapp
  namespace: default
spec:
  replicas: 4
  selector:
    matchLabels:
      tag: pythonapp
  template:
    metadata:
      labels:
        tag: pythonapp
    spec:
      containers:
        - name: udacitypythonapp
          image: ayamorsi/simple-python-app:latest
          ports:
            - containerPort: 8000
