apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      tag: pythonapp
  template:
    metadata:
      labels:
        tag: pythonapp
    spec:
      containers:
      - name: python-app
        image: ayamorsi/simple-python-app:latest
        ports:
        - containerPort: 8000
