apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    name: app-service
    app: pythonApp
spec:
  type: NodePort
  ports:
    - nodePort: 30001
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    name: python-app-deployment
    app: pythonApp
